import {renderNavbar} from "../components/navbar.js";import {renderFooter} from "../components/footer.js";import {requireAuthenticatedUser} from "../services/session-guard.js";import {createAdminAttraction,createAdminDestination,getAdminMessages,getAdminPlaces,getAdminSummary,updateAdminAttraction,updateAdminDestination,updateAdminMessage} from "../services/admin-service.js";
const user=await requireAuthenticatedUser("..");if(user.role!=="admin")location.replace("./profile.html");await renderNavbar("..",user);renderFooter();
const summaryEl=document.getElementById("admin-summary"),dList=document.getElementById("admin-destinations-list"),aList=document.getElementById("admin-attractions-list"),mList=document.getElementById("admin-messages-list"),status=document.getElementById("admin-status"),dialog=document.getElementById("admin-editor"),form=document.getElementById("admin-editor-form");let destinations=[],attractions=[],messages=[],activeTab="destinations";
const esc=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
async function load(){status.textContent="Loading…";try{const [s,d,a,m]=await Promise.all([getAdminSummary(),getAdminPlaces("destination"),getAdminPlaces("attraction"),getAdminMessages()]);destinations=d;attractions=a;messages=m;summaryEl.innerHTML=Object.entries(s).map(([k,v])=>`<div><strong>${v}</strong><span>${esc(k.replaceAll("_"," "))}</span></div>`).join("");render();status.textContent="";}catch(e){status.textContent=e.message;status.className="form-message form-message-error";}}
function recordCard(p,type){return `<article class="admin-record"><div><span class="tag">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.region)} · ${esc(p.district||"District not set")}</p></div><div class="admin-record-actions"><span class="admin-visibility ${p.isActive?"is-active":""}">${p.isActive?"Visible":"Hidden"}</span><button class="secondary-button" type="button" data-edit-type="${type}" data-edit-id="${p.id}">Edit</button></div></article>`;}
function render(){dList.innerHTML=destinations.map((p)=>recordCard(p,"destination")).join("");aList.innerHTML=attractions.map((p)=>recordCard(p,"attraction")).join("");mList.innerHTML=messages.length?messages.map((m)=>`<article class="admin-message"><header><div><strong>${esc(m.subject)}</strong><span>${esc(m.name)} · ${esc(m.email)}</span></div><select data-message-status="${m.id}"><option value="new" ${m.status==="new"?"selected":""}>New</option><option value="read" ${m.status==="read"?"selected":""}>Read</option><option value="closed" ${m.status==="closed"?"selected":""}>Closed</option></select></header><p>${esc(m.message)}</p><small>${new Date(m.createdAt).toLocaleString()}</small></article>`).join(""):`<div class="empty-state"><h3>No contact messages yet.</h3></div>`;}
function openEditor(type,place={}){document.getElementById("admin-editor-type").value=type;document.getElementById("admin-editor-id").value=place.id||"";document.getElementById("admin-editor-title").textContent=place.id?`Edit ${place.name}`:`New ${type}`;document.getElementById("admin-editor-name").value=place.name||"";document.getElementById("admin-editor-category").value=place.category||"";document.getElementById("admin-editor-region").value=place.region||"";document.getElementById("admin-editor-district").value=place.district||"";document.getElementById("admin-editor-parent").value=place.destinationId||"";document.getElementById("admin-editor-description").value=place.description||"";document.getElementById("admin-editor-highlight").value=place.highlight||"";document.getElementById("admin-editor-latitude").value=place.latitude??"";document.getElementById("admin-editor-longitude").value=place.longitude??"";document.getElementById("admin-editor-image").value=place.imageUrl||"";document.getElementById("admin-editor-active").checked=place.isActive!==false;dialog.showModal();}
document.addEventListener("click",(e)=>{const tab=e.target.closest("[data-admin-tab]");if(tab){activeTab=tab.dataset.adminTab;document.querySelectorAll("[data-admin-tab]").forEach(b=>b.classList.toggle("is-active",b===tab));document.getElementById("admin-destinations-panel").hidden=activeTab!=="destinations";document.getElementById("admin-attractions-panel").hidden=activeTab!=="attractions";document.getElementById("admin-messages-panel").hidden=activeTab!=="messages";}const edit=e.target.closest("[data-edit-id]");if(edit){const type=edit.dataset.editType,id=Number(edit.dataset.editId);openEditor(type,(type==="destination"?destinations:attractions).find(p=>p.id===id));}});
document.getElementById("admin-new-destination").onclick=()=>openEditor("destination");document.getElementById("admin-new-attraction").onclick=()=>openEditor("attraction");document.getElementById("admin-editor-close").onclick=()=>dialog.close();document.getElementById("admin-refresh").onclick=load;
form.addEventListener("submit",async(e)=>{e.preventDefault();const type=document.getElementById("admin-editor-type").value,id=Number(document.getElementById("admin-editor-id").value||0);const data={name:document.getElementById("admin-editor-name").value,category:document.getElementById("admin-editor-category").value,region:document.getElementById("admin-editor-region").value,district:document.getElementById("admin-editor-district").value||null,description:document.getElementById("admin-editor-description").value,highlight:document.getElementById("admin-editor-highlight").value||null,latitude:document.getElementById("admin-editor-latitude").value||null,longitude:document.getElementById("admin-editor-longitude").value||null,imageUrl:document.getElementById("admin-editor-image").value||null,isActive:document.getElementById("admin-editor-active").checked};if(type==="attraction")data.destinationId=document.getElementById("admin-editor-parent").value||null;try{if(type==="destination"){id?await updateAdminDestination(id,data):await createAdminDestination(data);}else{id?await updateAdminAttraction(id,data):await createAdminAttraction(data);}dialog.close();await load();}catch(err){status.textContent=err.message;status.className="form-message form-message-error";}});
mList.addEventListener("change",async(e)=>{const s=e.target.closest("[data-message-status]");if(!s)return;await updateAdminMessage(s.dataset.messageStatus,s.value);await load();});
await load();
